multiselect component additional requirements
bigbinary/neeto-ui-rn pull request #448
Opened 2022-08-24 12:13 UTC by injas-bigbinary

@Tsudhishnair _a

2022-08-25 06:28 UTC, Tsudhishnair commented
@injas-bigbinary 

- We need to specify a minimum height MultiSelect Input as `58px`.  Its specified in the [design System.](https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System?node-id=945%3A32546) 
![Screenshot 2022-08-25 at 11 10 27 AM](https://user-images.githubusercontent.com/25509500/186584363-891ffaf7-5349-4d42-80c7-5e9745efc2f0.png)

- The default color of the label should be `grey600` . 

- Currently the create button is shown even if we are searching for a option that's available in the list. 
![Screenshot 2022-08-25 at 11 19 50 AM](https://user-images.githubusercontent.com/25509500/186585124-6b4f530c-ea9b-4602-893a-dd702647ca8a.png)

-  SearchText is not trimmed before searching. ( Seems like an issue with the SearchBar component in neeto-ui-rn )

- We can have some default message shown when the `showCreateOption` is false and when the search result is empty. 

- Currently when the user clicks on the red area the bottomsheet is not getting opened. That area should dynamically grow based on the tags shown right, instead of specifying a specific width. 
![Screenshot 2022-08-25 at 11 53 04 AM](https://user-images.githubusercontent.com/25509500/186590430-c21525f5-9db7-47b8-848d-ad66ef7f8dfc.png)

2022-08-25 06:47 UTC, Tsudhishnair commented on src/components/MultiSelect.js
> +const Typography2 = styled.Text`
We can name this as `Typography` itself and remove the same from the above import and use it in the file.

2022-08-25 06:49 UTC, Tsudhishnair commented on src/components/MultiSelect.js
> +          // checkboxContainerProp={containerStyle}
We can remove this is not required.

2022-08-25 06:55 UTC, Tsudhishnair requested changes
@injas-bigbinary _a

2022-08-25 17:19 UTC, injas-bigbinary commented
@Tsudhishnair _a

https://user-images.githubusercontent.com/87293196/186728953-d15f7f95-0214-46cd-a4b3-25acc8d85213.mov

2022-08-25 17:23 UTC, injas-bigbinary commented
![Screenshot_1661448197](https://user-images.githubusercontent.com/87293196/186730058-85148c1d-c1cc-41da-af42-2dcd3c053dda.png)

2022-08-26 10:19 UTC, Tsudhishnair commented
@injas-bigbinary I have fixed https://github.com/bigbinary/neeto-ui-rn/pull/448#discussion_r954562807 in the last commit.
Rest of the changes made LGTM. Merging.

2022-08-26 10:19 UTC, merged