Add InputEmailChip component
bigbinary/neeto-ui-rn pull request #561
Opened 2023-01-03 17:58 UTC by chiragbhaiji

Fixes #560 

@sangameshsomawar please review

**Checklist**
- [ ] I have performed a self-review of my code and tested it well before raising the PR.
- [ ] I have made corresponding changes to the documentation and `index.d.ts`.
- [ ] I've verified the change via .yalc in neetoDesk.  

**Demo or Screenshots**

Demo link: https://app.usebubbles.com/vJnXyiKBRMoGM1qF34jpMA/input-email-chip-component-demo

<img  width="320" src="https://user-images.githubusercontent.com/27726339/210410874-8ea49e2e-00c9-4fb2-bfad-4205872b5e10.png" />

2023-01-05 10:22 UTC, sangameshsomawar requested changes

2023-01-05 10:22 UTC, sangameshsomawar commented on src/components/InputEmailChip.jsx
> +  const [emails, setEmails] = useState(initialEmails || []);
@chiragbhaiji 

https://app.usebubbles.com/cwEjgqgxQknywBJD8uwC1X/sangamesh-s-video-recording

2023-01-05 11:01 UTC, chiragbhaiji commented on storybook/stories/Chip.stories.jsx
> +      "Chip ComponentChip ComponentChip ComponentChip ComponentChip ComponentChip Component",
Sorry I was testing the case of long strings after making updates to the Chip component. Will revert it.

2023-01-06 09:36 UTC, chiragbhaiji commented
@sangameshsomawar _a I've updated and fixed things based on the provided feedback. Please review the changes and check [this issue](https://app.usebubbles.com/rfPwpb8ckqfA9P7fVNAu1e/chirag-s-video-recording) as it requires your input for the fix.

2023-01-06 11:34 UTC, sangameshsomawar approved these changes
@chiragbhaiji _a LGTM, please test once and merge.

2023-01-06 12:17 UTC, merged

2023-01-06 12:18 UTC, chiragbhaiji commented
> @chiragbhaiji _a LGTM, please test once and merge.

Tested it on Pixel 4a emulator and it looks good on that too. So merged it.